#pragma kernel CSMain

float4 vec;
RWTexture2D<float4> tex;
RWTexture2D<float4> tex1;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	if (distance(float4(vec.xy, 0, 0), float4(id.xy, 0, 0)) < 5) {
		if (tex[id.xy].r < 0.0001 && tex[id.xy].g < 0.0001) {
			tex1[id.xy] = float4(vec.z, vec.w, 1, 1);
		}
		tex[id.xy] = float4(vec.z, vec.w, (5 - distance(float4(vec.xy, 0, 0), float4(id.xy, 0, 0))) / 5, (5 - distance(float4(vec.xy, 0, 0), float4(id.xy, 0, 0))) / 5);
	}
}
