#pragma kernel CSMain

struct Pixel {
	float2 pos;
	float2 vec;
	int inside;
};

RWStructuredBuffer<Pixel> date;
int size;
float2 SizeMap;

[numthreads(32, 32, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	int i = id.x + id.y * 4096;
	if (i < size) {
		date[i].pos += date[id.x].vec;
		if (date[i].pos.x <= 0 || date[i].pos.y <= 0 ||
			date[i].pos.x >= SizeMap.x || date[i].pos.y >= SizeMap.y) {
			date[i].inside = 0;
		}
	}
}
